# Generated by Django 4.2.23 on 2025-06-22 06:59

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='*Allowed names contain letters, digits, spaces, and hyphens.', max_length=110, unique=True, validators=[profiles.models.validate_company_name])),
                ('phone_number', models.CharField(error_messages={'unique': 'That phone number is already in use!'}, max_length=15, unique=True, validators=[profiles.models.validate_phone_number])),
                ('secret_key', models.CharField(help_text='*Pick a combination of 4 unique digits.', max_length=4, validators=[profiles.models.validate_secret_key])),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
