# Generated by Django 4.2.23 on 2025-06-22 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_tickets', models.PositiveIntegerField(default=0)),
                ('key_features', models.TextField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='profiles.organizer')),
            ],
        ),
    ]
